libexec/tlenv-hooks: reverted to rbenv v1.2.0

diff --git a/libexec/tlenv-hooks b/libexec/tlenv-hooks
--- a/libexec/tlenv-hooks
+++ b/libexec/tlenv-hooks
@@ -21,12 +21,43 @@ if [ -z "$TLENV_COMMAND" ]; then
   exit 1
 fi
 
-IFS=: read -r -a hook_paths <<<"$TLENV_HOOK_PATH"
+if ! enable -f "${BASH_SOURCE%/*}"/tlenv-realpath.dylib realpath 2>/dev/null; then
+  if [ -n "$TLENV_NATIVE_EXT" ]; then
+    echo "tlenv: failed to load \`realpath' builtin" >&2
+    exit 1
+  fi
+READLINK=$(type -p greadlink readlink 2>/dev/null | head -n1)
+if [ -z "$READLINK" ]; then
+  echo "tlenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
+
+resolve_link() {
+  $READLINK "$1"
+}
+
+realpath() {
+  local cwd="$PWD"
+  local path="$1"
+  local name
+
+  while [ -n "$path" ]; do
+    name="${path##*/}"
+    [ "$name" = "$path" ] || cd "${path%/*}"
+    path="$(resolve_link "$name" || true)"
+  done
+
+  echo "${PWD}/$name"
+  cd "$cwd"
+}
+fi
+
+IFS=: hook_paths=($TLENV_HOOK_PATH)
 
 shopt -s nullglob
 for path in "${hook_paths[@]}"; do
   for script in "$path/$TLENV_COMMAND"/*.bash; do
-    echo "$script"
+    realpath "$script"
   done
 done
 shopt -u nullglob
